[project]
name = "pulseaudio-lambda-ml"
version = "0.0.1"
authors = [
  { name="Harry Askham", email="harryaskham@gmail.com" },
]
description = "ML models for use as PulseAudio Lambdas"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "torch==2.8.0",
    "torchaudio==2.8.0",
    "torchcodec",
    "triton>=2.8.0",
    "accelerate>=1.10.0",
    "numba>=0.57.0",
    "llvmlite>=0.40.0",
    "HS-TasNet>=0.2.29",
    "fire",
    "wandb",
]

[[tool.uv.index]]
name = "pytorch-rocm"
url = "https://download.pytorch.org/whl/rocm6.4"
explicit = true

# env | rg "(HIP|HCC|HSA|GPUS|ROCM|FLASH)"
[tool.uv.extra-build-variables]
flash-attn = {HCC_AMDGPU_TARGET = "gfx1100", HIP_VISIBLE_DEVICES = "0,1", HSA_OVERRIDE_GFX_VERSION = "11.0.0", GPUS_ARCH = "gfx1100", PYTORCH_ROCM_ARCH = "gfx1100" }

[tool.uv.sources]
torch = [{ index = "pytorch-rocm" }]
torchaudio = [{ index = "pytorch-rocm" }]
torchvision = [{ index = "pytorch-rocm" }]
triton = [{ index = "pytorch-rocm" }]

[tool.setuptools.packages.find]
where = ["."]
