#!/usr/bin/env bash

# Test lambda to check environment variables
echo "PA_LAMBDA_SAMPLE_RATE=$PA_LAMBDA_SAMPLE_RATE" >&2
echo "PA_LAMBDA_CHANNELS=$PA_LAMBDA_CHANNELS" >&2
echo "PA_LAMBDA_BUFFER_SIZE=$PA_LAMBDA_BUFFER_SIZE" >&2
echo "PA_LAMBDA_SAMPLE_FORMAT=$PA_LAMBDA_SAMPLE_FORMAT" >&2
echo "PA_LAMBDA_BYTES_PER_SAMPLE=$PA_LAMBDA_BYTES_PER_SAMPLE" >&2
echo "PA_LAMBDA_BYTES_PER_FRAME=$PA_LAMBDA_BYTES_PER_FRAME" >&2
echo "PA_LAMBDA_SIGNED=$PA_LAMBDA_SIGNED" >&2
echo "PA_LAMBDA_BITS=$PA_LAMBDA_BITS" >&2

# Still act as identity passthrough
exec cat